"""System-engineering and complementary risk-analysis conformance profiles.

Objective text is original navigation guidance. Controlled normative copies,
tailoring, applicability, and conformity decisions remain project-owned.
"""

from __future__ import annotations

from typing import Any


def _objective(
    identifier: str, title: str, locator: str, *evidence: str
) -> dict[str, Any]:
    return {
        "id": identifier,
        "title": title,
        "reference_locator": locator,
        "expected_evidence": list(evidence),
    }


def _profile(
    identifier: str,
    title: str,
    publisher: str,
    edition: str,
    url: str,
    scope: str,
    objectives: list[dict[str, Any]],
    *,
    access: str = "licensed_normative_text_required",
) -> dict[str, Any]:
    return {
        "id": identifier,
        "title": title,
        "publisher": publisher,
        "edition": edition,
        "status": "current",
        "reference_url": url,
        "access": access,
        "scope": scope,
        "objectives": objectives,
    }


SYSTEM_STANDARD_PROFILES: tuple[dict[str, Any], ...] = (
    _profile(
        "iso-29148-2018",
        "ISO/IEC/IEEE 29148:2018 requirements engineering",
        "ISO, IEC, and IEEE",
        "2018, confirmed 2024; revision in progress",
        "https://www.iso.org/standard/72089.html",
        "Requirements processes, characteristics, information items, traceability, and change.",
        [
            _objective("REQ-CONTEXT", "Define stakeholders, operational concepts, boundaries, assumptions, constraints, and external interfaces.", "requirements context and concepts", "stakeholder needs", "operational concept", "boundary and interface record"),
            _objective("REQ-QUALITY", "Specify necessary, implementation-free, unambiguous, feasible, verifiable, singular, and uniquely identified requirements.", "requirements characteristics", "quality-reviewed requirements", "review findings"),
            _objective("REQ-TRACE", "Maintain bidirectional traceability from stakeholder needs through system/software requirements, architecture, risks, and verification.", "traceability and allocation", "trace matrix", "coverage and orphan report"),
            _objective("REQ-VERIFY", "Define verification methods, acceptance criteria, rationale, and evidence for every applicable requirement.", "verification and validation", "verification plan", "acceptance criteria", "results"),
            _objective("REQ-CHANGE", "Control requirement baselines, changes, impact analysis, approvals, and unresolved issues.", "configuration and change management", "baseline index", "change-impact records", "approval history"),
        ],
    ),
    _profile(
        "iso-42010-2022",
        "ISO/IEC/IEEE 42010:2022 architecture description",
        "ISO, IEC, and IEEE",
        "2022",
        "https://www.iso.org/standard/74393.html",
        "Architecture descriptions, stakeholders, concerns, viewpoints, views, and correspondence.",
        [
            _objective("ARCH-SCOPE", "Identify the entity of interest, architecture purpose, stakeholders, concerns, environment, and lifecycle context.", "architecture-description context", "architecture charter", "stakeholder and concern register"),
            _objective("ARCH-VIEWPOINT", "Define each viewpoint, model kind, conventions, methods, stakeholders, concerns, and fitness criteria.", "architecture viewpoints", "viewpoint definitions", "model-kind definitions"),
            _objective("ARCH-VIEWS", "Provide views that conform to their viewpoints and address every declared concern.", "architecture views", "architecture models", "concern coverage"),
            _objective("ARCH-CORRESPONDENCE", "Record correspondence rules, model relationships, inconsistencies, decisions, rationale, and known limitations.", "correspondences and rationale", "correspondence report", "decision log", "inconsistency register"),
        ],
    ),
    _profile(
        "iso-15288-2023",
        "ISO/IEC/IEEE 15288:2023 system life cycle processes",
        "ISO, IEC, and IEEE",
        "2023",
        "https://www.iso.org/standard/81702.html",
        "System lifecycle agreement, organizational, technical-management, and technical processes.",
        [
            _objective("SYS-TAILOR", "Select and tailor lifecycle processes for the system, constituent systems, software elements, suppliers, and lifecycle stages.", "lifecycle model and tailoring", "approved lifecycle model", "tailoring record"),
            _objective("SYS-DEFINITION", "Transform stakeholder needs into system requirements, architecture, interfaces, allocation, and enabling-system needs.", "system definition processes", "needs", "requirements", "architecture", "interface agreements"),
            _objective("SYS-REALIZATION", "Integrate, verify, transition, validate, operate, maintain, and dispose of the system with retained evidence.", "system realization processes", "integration and V&V evidence", "transition and operation records"),
            _objective("SYS-MANAGEMENT", "Control decisions, risks, configuration, information, measurements, quality, changes, and technical reviews across organizations.", "technical-management processes", "risk and decision registers", "configuration status", "review records"),
        ],
    ),
    _profile(
        "iso-15289-2019",
        "ISO/IEC/IEEE 15289:2019 lifecycle information items",
        "ISO, IEC, and IEEE",
        "2019, confirmed 2025; revision in progress",
        "https://www.iso.org/standard/74909.html",
        "Purpose and content governance for system and software lifecycle information items.",
        [
            _objective("INFO-PLAN", "Identify required policies, plans, procedures, specifications, descriptions, records, requests, and reports.", "information-item planning", "information management plan", "deliverable index"),
            _objective("INFO-CONTENT", "Define controlled purpose, audience, required content, source, owner, status, format, and retention for each information item.", "generic and specific information-item content", "content specifications", "ownership and retention matrix"),
            _objective("INFO-CONTROL", "Maintain identification, version, review, approval, distribution, access, change, archive, and disposition controls.", "information management", "configuration records", "approval and distribution history"),
            _objective("INFO-TRACE", "Map lifecycle processes and decisions to the exact information items that supply or retain their evidence.", "process-to-information mapping", "process evidence matrix", "missing-information report"),
        ],
    ),
    _profile(
        "iso-16085-2021",
        "ISO/IEC/IEEE 16085:2021 systems and software risk management",
        "ISO, IEC, and IEEE",
        "2021",
        "https://www.iso.org/standard/74371.html",
        "Lifecycle risk-management process and required information items.",
        [
            _objective("RISK-PLAN", "Establish context, responsibilities, categories, parameters, thresholds, communication, resources, and review cadence.", "risk-management planning", "risk-management plan", "approved criteria"),
            _objective("RISK-ASSESS", "Identify, analyze, and evaluate threats and opportunities using traceable evidence, uncertainty, and defined criteria.", "risk assessment", "risk register", "analysis rationale", "uncertainty record"),
            _objective("RISK-TREAT", "Select, implement, verify, and monitor treatments with owners, dates, residual-risk evaluation, and acceptance authority.", "risk treatment", "treatment plan", "effectiveness evidence", "residual-risk decision"),
            _objective("RISK-MONITOR", "Continuously monitor indicators, assumptions, changes, emerging risks, treatment effectiveness, and escalation triggers.", "risk monitoring and communication", "risk status reports", "trigger history", "review records"),
        ],
    ),
    _profile(
        "iso-31000-2018",
        "ISO 31000:2018 organizational risk management",
        "ISO",
        "2018, confirmed 2023; revision in progress",
        "https://www.iso.org/standard/65694.html",
        "Organizational risk principles, framework, process, governance, and continual improvement.",
        [
            _objective("ISO31000-GOV", "Integrate risk management into governance, leadership, strategy, objectives, culture, and accountability.", "principles and framework", "risk policy", "accountability model", "governance reviews"),
            _objective("ISO31000-SCOPE", "Define internal/external context, scope, objectives, stakeholders, criteria, and communication arrangements.", "scope, context, and criteria", "context record", "risk criteria", "communication plan"),
            _objective("ISO31000-PROCESS", "Identify, analyze, evaluate, treat, monitor, review, record, and report risks through a repeatable process.", "risk process", "risk register", "treatment and monitoring evidence"),
            _objective("ISO31000-IMPROVE", "Evaluate framework effectiveness and adapt controls, resources, methods, and criteria as context and evidence change.", "evaluation and improvement", "effectiveness measures", "improvement actions"),
        ],
    ),
    _profile(
        "iec-31010-2019",
        "IEC 31010:2019 risk assessment techniques",
        "IEC",
        "2019",
        "https://webstore.iec.ch/en/publication/59809",
        "Selection, application, combination, and communication of risk-assessment techniques.",
        [
            _objective("RA-SELECT", "Select techniques appropriate to the decision, lifecycle phase, complexity, uncertainty, data, resources, and stakeholders.", "technique selection", "selection rationale", "competence and data assessment"),
            _objective("RA-APPLY", "Define assumptions, inputs, models, scales, dependencies, uncertainty, limitations, and reproducible procedures.", "technique application", "analysis procedure", "input and assumption register"),
            _objective("RA-COMBINE", "Combine complementary inductive, deductive, qualitative, quantitative, human, and system techniques without double counting evidence.", "combined techniques", "analysis integration map", "dependency rationale"),
            _objective("RA-REVIEW", "Validate models and results, perform sensitivity and uncertainty review, communicate limitations, and update after change.", "review and reporting", "independent review", "sensitivity results", "change history"),
        ],
    ),
    _profile(
        "iec-61025-2006",
        "IEC 61025:2006 fault tree analysis",
        "IEC",
        "2006, stability date 2029",
        "https://webstore.iec.ch/en/publication/4311",
        "Deductive fault-tree scope, logic, events, assumptions, evaluation, and reporting.",
        [
            _objective("FTA-DEFINE", "Define the top event, system boundary, mission/operating states, success criteria, assumptions, exclusions, and stopping rules.", "FTA definition", "top-event specification", "boundary and assumption register"),
            _objective("FTA-CONSTRUCT", "Develop reviewed event and gate logic with unique identities, transfer references, dependencies, common causes, and traceable sources.", "fault-tree construction", "fault-tree model", "event dictionary", "source trace"),
            _objective("FTA-EVALUATE", "Perform applicable qualitative or quantitative evaluation, minimal-cut-set review, importance/sensitivity analysis, and uncertainty treatment.", "FTA evaluation", "cut sets", "calculation and uncertainty evidence"),
            _objective("FTA-VERIFY", "Check logic completeness, consistency, independence assumptions, model configuration, results, limitations, and change impact.", "FTA verification and reporting", "model review", "verification record", "results report"),
        ],
    ),
    _profile(
        "iec-62502-2010",
        "IEC 62502:2010 event tree analysis",
        "IEC",
        "2010, stability date 2027",
        "https://webstore.iec.ch/en/publication/7131",
        "Initiating events, safety-function sequences, consequence states, dependencies, and evaluation.",
        [
            _objective("ETA-DEFINE", "Define initiating events, boundaries, time horizon, operating states, consequence criteria, and analysis assumptions.", "ETA scope", "initiating-event register", "consequence criteria"),
            _objective("ETA-SEQUENCE", "Model ordered success/failure branches for functions and controls, including dependencies, timing, recovery, and common causes.", "event-tree construction", "event-tree model", "branch and dependency definitions"),
            _objective("ETA-EVALUATE", "Evaluate sequence outcomes using applicable qualitative or quantitative evidence without unjustified independence assumptions.", "sequence evaluation", "sequence results", "probability and uncertainty basis"),
            _objective("ETA-REVIEW", "Verify completeness, logic, data, control effectiveness, consequence mapping, sensitivity, limitations, and change impact.", "ETA review and reporting", "independent review", "results and limitations"),
        ],
    ),
    _profile(
        "iec-62740-2015",
        "IEC 62740:2015 root cause analysis",
        "IEC",
        "2015, stability date 2029",
        "https://webstore.iec.ch/en/publication/21810",
        "A-posteriori event definition, evidence preservation, causal analysis, actions, and learning.",
        [
            _objective("RCA-INITIATE", "Define the focus event, impact, scope, team, authority, urgency, evidence-preservation actions, and investigation plan.", "RCA initiation", "event statement", "investigation plan", "evidence log"),
            _objective("RCA-ANALYZE", "Establish chronology, conditions, barriers, contributing factors, causal hypotheses, evidence, and uncertainty using suitable techniques.", "RCA analysis", "timeline", "causal model", "hypothesis evidence"),
            _objective("RCA-CONFIRM", "Distinguish root, contributing, and apparent causes and validate causal claims against facts and counter-evidence.", "cause validation", "validated cause set", "counter-evidence review"),
            _objective("RCA-ACT", "Select systemic corrective actions, verify effectiveness and unintended effects, share lessons, and monitor recurrence.", "corrective action and learning", "action register", "effectiveness evidence", "lessons learned"),
        ],
    ),
    _profile(
        "omg-sysml-2-2025",
        "OMG Systems Modeling Language 2.0 and Systems Modeling API 1.0",
        "Object Management Group",
        "SysML 2.0 and Systems Modeling API 1.0, September 2025",
        "https://www.omg.org/spec/SysML/2.0",
        "Machine-readable system architecture, requirements, behavior, interfaces, allocations, and model exchange.",
        [
            _objective("SYSML-MODEL", "Maintain uniquely identified system definitions, usages, requirements, interfaces, behaviors, states, and constraints in a controlled model baseline.", "SysML language and KerML semantics", "controlled model baseline", "element identity and ownership report"),
            _objective("SYSML-TRACE", "Preserve explicit satisfy, verify, allocate, refine, derive, and dependency relationships across system and software model elements.", "relationships and requirements", "relationship matrix", "unresolved-reference report"),
            _objective("SYSML-API", "Exchange model elements through the standardized API with declared project, commit, query, pagination, and version semantics.", "Systems Modeling API and Services", "API snapshot", "query and pagination evidence", "source commit identity"),
            _objective("SYSML-ROUNDTRIP", "Demonstrate identifier, type, property, relationship, and extension preservation through an independent model-tool round trip.", "model interchange and API conformance", "validator result", "receiving-tool round-trip evidence"),
        ],
        access="public_specification",
    ),
    _profile(
        "oasis-oslc-lifecycle-2022",
        "OASIS OSLC lifecycle integration (RM 2.1, QM 2.1, AM 3.0)",
        "OASIS Open Services for Lifecycle Collaboration",
        "RM 2.1, QM 2.1, and AM 3.0",
        "https://www.open-services.net/specifications/",
        "Linked lifecycle resources for requirements, architecture, verification plans, cases, and results.",
        [
            _objective("OSLC-DISCOVERY", "Provide or consume declared service-provider, creation, query, resource-shape, version, and pagination capabilities.", "OSLC Core discovery and domain conformance", "service-provider catalog", "capability and shape records"),
            _objective("OSLC-RM", "Preserve requirements, collections, identities, properties, links, and unknown content according to the RM resource shapes.", "OSLC Requirements Management 2.1", "RM resource snapshot", "shape-validation result"),
            _objective("OSLC-QM", "Relate test plans, test cases, test scripts, execution records, and results to their verified requirements.", "OSLC Quality Management 2.1", "QM resource snapshot", "requirement-to-test trace"),
            _objective("OSLC-AM", "Relate architecture resources and their links to requirements, implementation components, hazards, and verification evidence.", "OSLC Architecture Management 3.0", "AM resource snapshot", "architecture trace"),
        ],
        access="public_specification",
    ),
    _profile(
        "iec-61882-2016",
        "IEC 61882:2016 hazard and operability studies",
        "IEC",
        "2016, stability date 2028",
        "https://webstore.iec.ch/en/publication/24321",
        "Guide-word-based HAZOP definition, preparation, examination, documentation, and follow-up.",
        [
            _objective("HAZOP-DEFINE", "Define study purpose, boundaries, nodes, design intent, operating modes, assumptions, team competence, and guide-word vocabulary.", "study definition and preparation", "HAZOP plan", "node and design-intent register"),
            _objective("HAZOP-EXAMINE", "Apply each applicable guide word to each parameter and retain deviations, causes, consequences, safeguards, detectability, and recommendations.", "examination sessions", "HAZOP worksheet", "session record"),
            _objective("HAZOP-FOLLOWUP", "Assign actions, resolve recommendations, verify safeguard effectiveness, accept residual risk, and update the study after change.", "documentation and follow-up", "action register", "effectiveness evidence", "residual-risk decision"),
        ],
    ),
    _profile(
        "iec-61078-2016",
        "IEC 61078:2016 reliability block diagrams",
        "IEC",
        "2016",
        "https://webstore.iec.ch/en/publication/25647",
        "Reliability block diagram construction, success logic, dependencies, calculation, sensitivity, and reporting.",
        [
            _objective("RBD-DEFINE", "Define success criteria, mission profile, boundaries, operating states, repair assumptions, and data provenance.", "RBD scope and assumptions", "success criteria", "mission and data record"),
            _objective("RBD-MODEL", "Construct reviewed series, parallel, standby, voting, shared-cause, and dependency relationships without unjustified independence.", "RBD construction", "block diagram", "dependency and common-cause register"),
            _objective("RBD-EVALUATE", "Calculate applicable reliability or availability measures with uncertainty, sensitivity, limitations, and independently reproducible inputs.", "RBD evaluation", "calculation record", "sensitivity and uncertainty results"),
        ],
    ),
    _profile(
        "iec-61165-2006",
        "IEC 61165:2006 application of Markov techniques",
        "IEC",
        "2006, stability date 2027",
        "https://webstore.iec.ch/en/publication/4721",
        "State-dependent reliability, availability, maintainability, and safety modeling using homogeneous Markov techniques.",
        [
            _objective("MARKOV-DEFINE", "Define states, transitions, absorbing conditions, mission horizon, rate assumptions, rewards, initial conditions, and applicability limits.", "model definition", "state dictionary", "transition and rate basis"),
            _objective("MARKOV-SOLVE", "Solve the declared model reproducibly and report state probabilities and applicable reliability, availability, maintainability, or safety measures.", "model solution", "solver record", "time-indexed results"),
            _objective("MARKOV-VALIDATE", "Check conservation, reachability, units, rate sensitivity, numerical stability, data provenance, and comparison with independent calculations or observations.", "verification and validation", "validation report", "sensitivity and comparison evidence"),
        ],
    ),
    _profile(
        "iso-5055-25023-quality-measurement",
        "ISO/IEC 5055:2021 and ISO/IEC 25023:2016 software quality measurement",
        "ISO and IEC",
        "5055:2021 and 25023:2016 (25023 revision in progress)",
        "https://www.iso.org/standard/80623.html",
        "Automated source-code quality measures and product-quality measures aligned with the SQuaRE quality model.",
        [
            _objective("QUALITY-MODEL", "Select applicable product-quality characteristics, measures, measurement elements, target entities, scales, and decision criteria.", "ISO/IEC 25023 measurement model", "quality measurement plan", "measure definitions"),
            _objective("QUALITY-SOURCE", "Measure architectural and coding-practice violations using controlled detection rules, aggregation, normalization, and scope.", "ISO/IEC 5055 automated source-code measures", "rule catalog", "source-quality measurements"),
            _objective("QUALITY-VALIDATE", "Demonstrate measurement reliability, validity, repeatability, uncertainty, limitations, and change control on representative software.", "measurement validation", "repeatability study", "independent benchmark evidence"),
        ],
    ),
    _profile(
        "ieee-1012-2024",
        "IEEE 1012-2024 system, software, and hardware verification and validation",
        "IEEE",
        "2024; revision project active",
        "https://standards.ieee.org/ieee/1012/12536/",
        "Integrity-level verification and validation processes across lifecycle products, interfaces, reuse, and operational context.",
        [
            _objective("VNV-PLAN", "Define V&V scope, integrity level, lifecycle tasks, independence, responsibilities, inputs, outputs, methods, schedule, and acceptance criteria.", "V&V planning", "V&V plan", "integrity-level rationale"),
            _objective("VNV-EXECUTE", "Perform traceable analysis, evaluation, review, inspection, assessment, and testing of applicable lifecycle products and interfaces.", "V&V processes", "procedure and result set", "anomaly records"),
            _objective("VNV-INDEPENDENCE", "Establish and retain the technical, managerial, and financial independence required by the selected integrity level and decision context.", "V&V organization and integrity levels", "independence record", "competence evidence"),
            _objective("VNV-REPORT", "Reconcile V&V coverage, anomalies, deviations, limitations, unresolved risk, conclusions, and approval for the exact baseline.", "V&V reporting", "summary report", "baseline evidence index"),
        ],
    ),
    _profile(
        "oasis-csaf-2-0",
        "OASIS Common Security Advisory Framework 2.0",
        "OASIS",
        "2.0 with Errata 01",
        "https://docs.oasis-open.org/csaf/csaf/v2.0/",
        "Normative JSON security-advisory exchange for products, vulnerabilities, impact status, remediation, and document tracking.",
        [
            _objective("CSAF-DOCUMENT", "Publish a schema-valid advisory with controlled publisher, category, title, tracking, version, revision history, and release dates.", "CSAF document property", "CSAF document", "normative-schema validation result"),
            _objective("CSAF-PRODUCT", "Identify every referenced product unambiguously and preserve product-tree, relationship, version, and identification-helper semantics.", "CSAF product tree", "product identity register", "SBOM linkage"),
            _objective("CSAF-VULNERABILITY", "Record vulnerability identity, product status, justification, scores, threats, remediation, and references without contradictory status assignments.", "CSAF vulnerabilities", "advisory decision record", "status-conflict check"),
            _objective("CSAF-DISTRIBUTION", "Apply TLP, audience, redistribution, signature, publication, validation, and archival controls appropriate to the advisory category.", "CSAF distribution and conformance", "distribution record", "validator and signature evidence"),
        ],
        access="public_specification",
    ),
    _profile(
        "slsa-1-2",
        "Supply-chain Levels for Software Artifacts 1.2",
        "OpenSSF SLSA",
        "1.2",
        "https://slsa.dev/spec/v1.2/",
        "Build and source provenance, trusted builders, verification, and progressive supply-chain hardening.",
        [
            _objective("SLSA-PROVENANCE", "Produce authentic, non-forgeable provenance that identifies the artifact, source, build definition, builder, and dependencies.", "SLSA Build track and provenance", "provenance statement", "signature-verification evidence"),
            _objective("SLSA-BUILD", "Assess hosted, isolated, ephemeral, and parameter-controlled build practices against the selected Build track level.", "SLSA Build track", "builder trust policy", "build-platform control evidence"),
            _objective("SLSA-SOURCE", "Assess repository history, provenance, change approval, and review controls against the selected Source track level.", "SLSA Source track", "source-control policy", "repository audit evidence"),
            _objective("SLSA-VERIFY", "Verify artifact identity, provenance authenticity, trusted builder and signer identity, build constraints, and policy before use.", "SLSA artifact verification", "deny-by-default trust policy", "verification result"),
        ],
        access="public_specification",
    ),
    _profile(
        "iec-62443-4-2-2019",
        "IEC 62443-4-2:2019 industrial automation component security",
        "IEC",
        "2019",
        "https://webstore.iec.ch/en/publication/34421",
        "Technical security requirements for industrial automation and control system components.",
        [
            _objective("IACS-IDENTITY", "Specify identification, authentication, account, authenticator, and access-control behavior for every exposed component interface.", "foundational requirements 1 and 2", "security requirements", "access-control tests"),
            _objective("IACS-INTEGRITY", "Protect code, data, communications, audit records, and update paths from unauthorized modification and unsafe input.", "foundational requirements 3 and 4", "integrity architecture", "negative and tamper tests"),
            _objective("IACS-FLOW", "Restrict data flow, resource use, denial-of-service exposure, and availability degradation at component boundaries.", "foundational requirements 5 and 7", "zone and conduit mapping", "resource-exhaustion evidence"),
            _objective("IACS-EVENTS", "Generate, protect, synchronize, retain, and review security-relevant events with attributable evidence.", "foundational requirement 6", "event policy", "audit and monitoring evidence"),
        ],
    ),
    _profile(
        "cisa-ssvc",
        "CISA Stakeholder-Specific Vulnerability Categorization",
        "Cybersecurity and Infrastructure Security Agency",
        "current public guidance; verify controlled version at use",
        "https://www.cisa.gov/stakeholder-specific-vulnerability-categorization-ssvc",
        "Evidence-based vulnerability prioritization using stakeholder-specific decision points and outcomes.",
        [
            _objective("SSVC-SCOPE", "Declare stakeholder role, decision model version, decision date, asset scope, and accountable decision authority.", "SSVC model selection", "controlled decision tree", "authority record"),
            _objective("SSVC-EVIDENCE", "Collect attributable evidence for exploitation, technical impact, mission prevalence, public well-being, and other selected decision points.", "SSVC decision points", "evidence packet", "source and timestamp record"),
            _objective("SSVC-DECIDE", "Apply the exact decision tree reproducibly and retain the resulting action, rationale, uncertainty, and reassessment triggers.", "SSVC decision outcome", "machine-verifiable decision record", "review history"),
        ],
        access="public_guidance",
    ),
    _profile(
        "iso-5259-data-quality",
        "ISO/IEC 5259 artificial-intelligence data quality series",
        "ISO and IEC",
        "Parts 2, 3, and 5 published; verify applicable controlled editions",
        "https://www.iso.org/standard/81860.html",
        "Data-quality models, management requirements, governance, and measurement for analytics and machine learning.",
        [
            _objective("AI-DATA-MODEL", "Select data-quality characteristics, measures, thresholds, populations, and intended-use constraints for training, validation, test, and operational data.", "ISO/IEC 5259-2 and 5259-3", "data-quality model", "measurement specification"),
            _objective("AI-DATA-GOVERN", "Control provenance, collection, labeling, consent, representativeness, leakage, transformation, lineage, access, retention, and change.", "ISO/IEC 5259-5", "data governance plan", "lineage and approval records"),
            _objective("AI-DATA-MONITOR", "Measure drift, subgroup behavior, missingness, contamination, uncertainty, and fitness for use over the lifecycle.", "ISO/IEC 5259 measurement and management", "monitoring results", "corrective-action record"),
        ],
    ),
    _profile(
        "iso-25059-ai-quality",
        "ISO/IEC 25059:2023 quality model for AI systems",
        "ISO and IEC",
        "2023; successor edition under development",
        "https://www.iso.org/standard/80655.html",
        "AI system and software product quality characteristics within the SQuaRE family.",
        [
            _objective("AI-QUALITY-CONTEXT", "Define intended use, affected stakeholders, operating conditions, unacceptable behavior, autonomy boundaries, and human oversight.", "AI quality context", "intended-use specification", "stakeholder and harm analysis"),
            _objective("AI-QUALITY-MEASURE", "Select measurable AI quality characteristics, subgroup criteria, robustness conditions, uncertainty, and acceptance thresholds.", "AI quality model", "quality measurement plan", "evaluation protocol"),
            _objective("AI-QUALITY-LIFECYCLE", "Retain evaluation, monitoring, incident, change-impact, retraining, rollback, and retirement evidence for the exact model and data versions.", "AI lifecycle quality", "model and data cards", "monitoring and change records"),
        ],
    ),
    _profile(
        "iso-tr-5469-2024",
        "ISO/IEC TR 5469:2024 artificial intelligence and functional safety",
        "ISO and IEC",
        "2024",
        "https://www.iso.org/standard/81283.html",
        "Functional-safety properties, risk factors, lifecycle considerations, and assurance challenges for AI technology.",
        [
            _objective("AI-FS-ROLE", "Define the AI function, safety role, allocation, operating envelope, fallback, independence assumptions, and interaction with conventional safety mechanisms.", "AI and functional-safety concepts", "safety allocation", "operational design domain"),
            _objective("AI-FS-FAILURE", "Analyze systematic, data-dependent, distributional, performance-boundary, interaction, and common-cause failure behavior.", "AI failure and risk factors", "AI hazard analysis", "failure-mode evidence"),
            _objective("AI-FS-ASSURE", "Use diverse lifecycle evidence, independent evaluation, runtime monitoring, degraded modes, change control, and explicit residual-risk authority.", "AI assurance considerations", "assurance case", "runtime and change evidence"),
        ],
    ),
    _profile(
        "iso-15026-2-2022",
        "ISO/IEC/IEEE 15026-2:2022 assurance case",
        "ISO, IEC, and IEEE",
        "2022",
        "https://www.iso.org/standard/80625.html",
        "Minimum requirements for the structure and contents of assurance cases and their lifecycle use.",
        [
            _objective("CASE-SCOPE", "Define the assurance claim, system and lifecycle scope, decision context, authority, assumptions, and applicable criteria.", "assurance-case purpose and scope", "case charter", "decision and authority record"),
            _objective("CASE-ARGUE", "Provide explicit claims, argument strategies, evidence relationships, context, assumptions, justifications, and counter-evidence.", "assurance-case structure", "structured assurance case", "argument review record"),
            _objective("CASE-EVIDENCE", "Bind every evidence assertion to identified, versioned, attributable, and quality-assessed evidence with stated limitations.", "assurance evidence", "evidence index", "provenance and quality assessment"),
            _objective("CASE-MAINTAIN", "Control baselines, changes, unresolved defeaters, approvals, review independence, and continued validity over the lifecycle.", "assurance-case lifecycle", "change-impact record", "review and approval history"),
        ],
    ),
    _profile(
        "iso-5338-2023",
        "ISO/IEC 5338:2023 AI system life cycle processes",
        "ISO and IEC",
        "2023",
        "https://www.iso.org/standard/81118.html",
        "Integration of AI-specific processes into organizational and system life cycles.",
        [
            _objective("AI-LC-TAILOR", "Define and tailor the AI lifecycle, roles, stage gates, suppliers, data and model responsibilities, and interfaces to system and software processes.", "AI lifecycle tailoring", "approved lifecycle model", "responsibility matrix"),
            _objective("AI-LC-REALIZE", "Control data acquisition, preparation, model development, evaluation, integration, verification, validation, deployment, and transition.", "AI technical processes", "data and model baselines", "evaluation and release evidence"),
            _objective("AI-LC-OPERATE", "Monitor intended use, performance, drift, incidents, human oversight, updates, rollback, retirement, and downstream impacts in operation.", "AI operation and maintenance", "monitoring plan", "incident and change records"),
            _objective("AI-LC-ASSURE", "Maintain risk, configuration, quality, measurement, decision, information, and assurance evidence across the AI lifecycle.", "AI technical management", "risk and assurance case", "configuration and review evidence"),
        ],
    ),
    _profile(
        "iso-42005-2025",
        "ISO/IEC 42005:2025 AI system impact assessment",
        "ISO and IEC",
        "2025",
        "https://www.iso.org/standard/42005",
        "Organizational process for assessing impacts of AI systems on individuals, groups, and society.",
        [
            _objective("AI-IMPACT-CONTEXT", "Define the AI system, intended use, deployment context, affected people and groups, accountable roles, assumptions, and assessment triggers.", "impact-assessment context", "system and stakeholder scope", "authority record"),
            _objective("AI-IMPACT-ANALYZE", "Identify and analyze beneficial and adverse impacts, affected rights and interests, severity, likelihood, distribution, uncertainty, and cumulative effects.", "impact analysis", "impact register", "stakeholder evidence"),
            _objective("AI-IMPACT-TREAT", "Select controls, human oversight, recourse, communication, monitoring, acceptance criteria, and accountable residual-impact decisions.", "impact treatment", "control plan", "residual-impact decision"),
            _objective("AI-IMPACT-REVIEW", "Review and update the assessment after material system, data, context, performance, incident, or stakeholder changes.", "impact-assessment lifecycle", "monitoring and reassessment record", "change history"),
        ],
    ),
    _profile(
        "iso-pas-8800-2024",
        "ISO/PAS 8800:2024 safety and artificial intelligence in road vehicles",
        "ISO",
        "2024",
        "https://www.iso.org/standard/83303.html",
        "Safety-related properties and risk management for AI elements in road-vehicle applications.",
        [
            _objective("ROAD-AI-SCOPE", "Define the AI element, vehicle-level safety role, operational design domain, allocation, interfaces, assumptions, fallback, and change boundary.", "AI safety lifecycle scope", "safety plan", "ODD and allocation record"),
            _objective("ROAD-AI-RISK", "Analyze hazardous behavior from data, model, specification, performance, interaction, misuse, uncertainty, and distribution shift, including common causes.", "AI safety risk analysis", "hazard and failure analysis", "scenario catalogue"),
            _objective("ROAD-AI-EVIDENCE", "Use representative data and scenarios, measurable safety requirements, independent evaluation, robustness evidence, uncertainty bounds, and traceable verification.", "AI safety assurance", "evaluation protocol", "verification and validation evidence"),
            _objective("ROAD-AI-OPS", "Monitor field performance, ODD compliance, degradation, incidents, updates, retraining, rollback, and continued safety-case validity.", "production and operation", "runtime monitoring", "change and incident evidence"),
        ],
    ),
    _profile(
        "ul-4600-edition-3",
        "UL 4600 Edition 3 autonomous products safety evaluation",
        "UL Standards & Engagement",
        "Edition 3",
        "https://www.ul.com/news/ul-4600-edition-3-updates-incorporate-autonomous-trucking",
        "Safety-case-oriented evaluation of autonomous products without a human driver or operator fallback.",
        [
            _objective("AUTO-CASE", "Maintain a structured safety case covering the autonomous system, intended missions, operational domain, hazards, mitigations, evidence, assumptions, and residual risk.", "safety-case framework", "controlled safety case", "review and acceptance record"),
            _objective("AUTO-HAZARD", "Use complementary hazard and failure analyses to address perception, planning, control, interactions, foreseeable misuse, degraded operation, and common causes.", "hazard analysis", "hazard log", "scenario and failure evidence"),
            _objective("AUTO-VERIFY", "Establish traceable verification and validation using analysis, simulation, test, field evidence, independence, coverage arguments, and explicit limitations.", "verification and validation", "evidence plan", "coverage and results"),
            _objective("AUTO-LIFECYCLE", "Control cybersecurity, safety culture, suppliers, configuration, updates, monitoring, incidents, learning, and continued safety-case validity.", "lifecycle assurance", "governance records", "field monitoring and change evidence"),
        ],
    ),
    _profile(
        "iso-25040-2024",
        "ISO/IEC 25040:2024 quality evaluation framework",
        "ISO and IEC",
        "2024",
        "https://www.iso.org/standard/83467.html",
        "Quality-evaluation requirements, specification, design, execution, and conclusion within SQuaRE.",
        [
            _objective("QE-REQUIRE", "Establish evaluation purpose, stakeholders, intended use, scope, quality requirements, acceptance criteria, and decision authority.", "evaluation requirements", "evaluation charter", "quality requirements"),
            _objective("QE-SPECIFY", "Select quality measures, methods, thresholds, uncertainty treatment, resources, responsibilities, tools, and controlled procedures before execution.", "evaluation specification and design", "evaluation plan", "measure specifications"),
            _objective("QE-EXECUTE", "Execute controlled measures, retain raw evidence and deviations, interpret results against criteria, and record an authorized conclusion with limitations.", "evaluation execution and conclusion", "measurement evidence", "evaluation report", "approval record"),
        ],
    ),
    _profile(
        "ieee-1633-2016",
        "IEEE 1633-2016 software reliability",
        "IEEE",
        "2016",
        "https://standards.ieee.org/ieee/1633/5726/",
        "Software reliability planning, prediction, measurement, assessment, and lifecycle evidence.",
        [
            _objective("REL-PLAN", "Define reliability objectives, operational profile, failure definition, measurement strategy, assumptions, responsibilities, and lifecycle activities.", "software reliability program planning", "reliability plan", "operational profile"),
            _objective("REL-MEASURE", "Collect configuration-controlled failure, exposure, repair, test, and field data with censoring, uncertainty, and data-quality controls.", "reliability measurement", "failure data", "exposure and data-quality evidence"),
            _objective("REL-ASSESS", "Apply justified reliability models, goodness-of-fit and sensitivity checks, growth analysis, predictions, limitations, and authorized decisions.", "reliability modeling and assessment", "model results", "validation and decision record"),
        ],
    ),
    _profile(
        "owasp-asvs-5-0",
        "OWASP Application Security Verification Standard 5.0",
        "OWASP Foundation",
        "5.0.0",
        "https://owasp.org/www-project-application-security-verification-standard/",
        "Application-security verification requirements and evidence organized by assurance level.",
        [
            _objective("ASVS-SCOPE", "Select the applicable ASVS version and level, define application boundaries, threat context, exclusions, and accountable verification authority.", "ASVS scope and level", "verification scope", "level rationale"),
            _objective("ASVS-VERIFY", "Map each applicable requirement identifier to reproducible design, code, configuration, or test evidence and retain failures and limitations.", "ASVS requirements", "requirement evidence matrix", "test results"),
            _objective("ASVS-MAINTAIN", "Control version changes, exceptions, remediation, regression evidence, dependency changes, and periodic reassessment.", "verification lifecycle", "exception register", "reassessment history"),
        ],
        access="public_guidance",
    ),
    _profile(
        "iso-27034-1-2011",
        "ISO/IEC 27034-1:2011 application security",
        "ISO and IEC",
        "2011, confirmed 2022",
        "https://www.iso.org/standard/44378.html",
        "Application-security concepts, organizational framework, management process, and application lifecycle controls.",
        [
            _objective("APPSEC-FRAME", "Establish the organizational normative framework, roles, application-security control library, risk criteria, and governance interfaces.", "organizational normative framework", "security policy", "control library"),
            _objective("APPSEC-RISK", "Define application context, identify risks, select and tailor controls, and retain traceability to requirements and architecture.", "application security management", "risk assessment", "application normative framework"),
            _objective("APPSEC-VERIFY", "Verify implemented controls through the lifecycle, control exceptions and changes, retain evidence, and authorize residual-risk decisions.", "application security lifecycle", "verification evidence", "exception and approval record"),
        ],
    ),
    _profile(
        "nist-ai-rmf-1-0",
        "NIST AI Risk Management Framework 1.0",
        "NIST",
        "1.0; revision in progress in 2026",
        "https://www.nist.gov/itl/ai-risk-management-framework",
        "Voluntary Govern, Map, Measure, and Manage functions for trustworthy and responsible AI risk.",
        [
            _objective("AIRMF-GOVERN", "Establish policies, roles, accountability, culture, competence, inventory, risk tolerance, documentation, and third-party governance.", "GOVERN", "AI governance policy", "roles and inventory"),
            _objective("AIRMF-MAP", "Establish context, intended purpose, affected stakeholders, impacts, dependencies, assumptions, lifecycle stage, and risk framing.", "MAP", "context and impact record", "stakeholder evidence"),
            _objective("AIRMF-MEASURE-MANAGE", "Measure prioritized risks and uncertainty with validated methods, then select, monitor, communicate, and revise treatments and decisions.", "MEASURE and MANAGE", "TEVV evidence", "risk treatment and monitoring record"),
        ],
        access="public_guidance",
    ),
    _profile(
        "iso-24029-robustness",
        "ISO/IEC 24029 neural-network robustness series",
        "ISO and IEC",
        "Parts 1 and 2; verify applicable controlled editions",
        "https://www.iso.org/artificial-intelligence/neural-networks",
        "Robustness concepts, assessment methods, and formal-method considerations for neural networks.",
        [
            _objective("NN-ROBUST-SCOPE", "Define the neural-network function, input domain, perturbation model, robustness property, operating conditions, assumptions, and unacceptable outcomes.", "robustness scope", "property specification", "input and perturbation model"),
            _objective("NN-ROBUST-ASSESS", "Select justified empirical or formal assessment methods, datasets, coverage, uncertainty, thresholds, tools, and independent review.", "robustness assessment", "TEVV protocol", "tool and dataset evidence"),
            _objective("NN-ROBUST-REPORT", "Report results, counterexamples, residual uncertainty, method limitations, configuration identity, and change-triggered reassessment.", "robustness reporting", "assessment report", "counterexample and change record"),
        ],
    ),
    _profile(
        "automotive-spice-4-0",
        "Automotive SPICE Process Assessment Model 4.0",
        "VDA QMC",
        "4.0",
        "https://www.vda.de/en/press/press-releases/2024/240710_PM_VDA_QMC_Automotive_SPICE_EN",
        "Automotive process-reference and assessment practices for system, software, support, and management processes.",
        [
            _objective("ASPICE-SCOPE", "Define assessment scope, process instances, organizational context, assessor competence, independence, evidence sampling, and rating rules.", "assessment planning", "assessment plan", "scope and competence record"),
            _objective("ASPICE-PROCESS", "Assess applicable base practices and work products using objective evidence across requirements, architecture, implementation, verification, validation, support, and management.", "process dimension", "evidence matrix", "interview and work-product record"),
            _objective("ASPICE-CAPABILITY", "Rate process attributes consistently, retain findings and rationale, calibrate assessors, control improvement actions, and independently review results.", "capability dimension", "rating record", "calibration and improvement evidence"),
        ],
        access="public_metadata_and_licensed_guidance",
    ),
    _profile(
        "faa-do-326a-ed-202a",
        "FAA aircraft cybersecurity process using DO-326A / ED-202A",
        "FAA and RTCA/EUROCAE",
        "FAA-recognized editions; verify applicable advisory material and controlled standards",
        "https://www.faa.gov/aircraft/air_cert/design_approvals/dah/cybersecurity",
        "Airworthiness security process, threat assessment, risk treatment, verification, and continued-airworthiness evidence.",
        [
            _objective("AIRSEC-SCOPE", "Define aircraft and system security scope, assets, interfaces, external dependencies, assumptions, certification basis, and coordination responsibilities.", "airworthiness security planning", "security plan", "asset and interface inventory"),
            _objective("AIRSEC-ASSESS", "Perform threat and security risk assessment, derive security requirements, allocate controls, and trace safety-security interactions and common causes.", "security risk assessment", "threat assessment", "requirements and allocation evidence"),
            _objective("AIRSEC-VERIFY", "Verify security requirements, penetration and robustness objectives, configuration, residual risk, changes, incidents, and continued-airworthiness obligations.", "security verification and continued airworthiness", "verification results", "approval and monitoring evidence"),
        ],
        access="public_faa_guidance_and_licensed_normative_text_required",
    ),
    _profile(
        "iec-82304-1-2016",
        "IEC 82304-1:2016 health software product safety",
        "IEC",
        "2016",
        "https://webstore.iec.ch/en/publication/26120",
        "General requirements for safety and security of health software products across the product lifecycle.",
        [
            _objective("HEALTHSW-REQ", "Define intended use, user and environment, product requirements, risk controls, security needs, labeling, and acceptance criteria.", "health software product requirements", "product requirements", "risk and security traceability"),
            _objective("HEALTHSW-VALIDATE", "Validate the complete health software product for intended use, including risk controls, usability, security, installation, maintenance, and accompanying documents.", "product validation", "validation plan and results", "release evidence"),
            _objective("HEALTHSW-MAINTAIN", "Control configuration, changes, maintenance, post-market information, incidents, problem resolution, updates, and retirement.", "product lifecycle", "configuration and maintenance records", "post-market evidence"),
        ],
    ),
    _profile(
        "iso-17025-2017",
        "ISO/IEC 17025:2017 testing and calibration laboratory competence",
        "ISO and IEC",
        "2017, confirmed 2023",
        "https://www.iso.org/standard/66912.html",
        "Competence, impartiality, consistent operation, method validity, traceability, and reporting for testing laboratories.",
        [
            _objective("LAB-IMPARTIAL", "Control impartiality, confidentiality, organizational responsibilities, competence, authorization, and conflicts of interest.", "structural and resource requirements", "role and competence records", "impartiality risk register"),
            _objective("LAB-METHOD", "Select, verify, and validate methods; control equipment and software; establish traceability, uncertainty, sampling, quality assurance, and proficiency evidence.", "process requirements", "method validation", "traceability and uncertainty evidence"),
            _objective("LAB-REPORT", "Control requests, samples, technical records, deviations, nonconforming work, complaints, results, amendments, audits, corrective actions, and management review.", "process and management-system requirements", "controlled report", "audit and corrective-action evidence"),
        ],
    ),
    _profile(
        "first-cvss-4-0",
        "FIRST Common Vulnerability Scoring System v4.0",
        "FIRST",
        "4.0",
        "https://www.first.org/cvss/v4.0/specification-document",
        "Canonical vulnerability metric vectors, score provenance, supplemental context, and severity communication.",
        [
            _objective("CVSS-VECTOR", "Record a canonical CVSS v4 vector with complete Base metrics and applicable Threat, Environmental, and Supplemental metrics.", "CVSS v4 vector string", "validated vector", "metric rationale"),
            _objective("CVSS-SCORE", "Retain calculator identity, version, input vector, score, qualitative severity, timestamp, and immutable calculation evidence.", "CVSS scoring", "calculator receipt", "score observation"),
            _objective("CVSS-DECIDE", "Keep CVSS severity distinct from asset context, exploitation evidence, safety or mission impact, treatment priority, disposition, and accountable decision authority.", "CVSS use and limitations", "prioritization record", "authorized disposition"),
        ],
        access="public_specification",
    ),
    _profile(
        "mit-stpa-cast",
        "MIT STPA and CAST handbooks",
        "MIT Partnership for Systems Approaches to Safety and Security",
        "current public handbooks; control the selected edition",
        "https://psas.scripts.mit.edu/home/books-and-handbooks/",
        "System-Theoretic Process Analysis and Causal Analysis based on Systems Theory methods.",
        [
            _objective("STPA-DEFINE", "Define losses, system-level hazards, safety or security constraints, system boundary, operating modes, assumptions, and a reviewed control structure.", "STPA foundations and Step 1", "loss and hazard register", "control-structure model"),
            _objective("STPA-UCA", "Identify unsafe control actions across omission, provision, timing/order, and duration contexts and trace each to hazards and constraints.", "STPA Step 1", "UCA table", "traceability review"),
            _objective("STPA-SCENARIO", "Develop loss scenarios covering controller behavior, process-model flaws, feedback, coordination, timing, physical process, requirements, mitigations, and tests.", "STPA Step 2", "loss scenarios", "requirements and test evidence"),
            _objective("CAST-LEARN", "For incidents, reconstruct the control structure, responsibilities, decisions, context, process-model and coordination factors, then assign systemic corrective actions without reducing analysis to operator blame.", "CAST handbook", "incident control analysis", "corrective-action and verification record"),
        ],
        access="public_guidance",
    ),
)
